In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
df = pd.read_csv("labeledTrainData.tsv", sep="	")
tf = pd.read_csv("testData.tsv", sep="	")

df

id  sentiment                                             review
0       5814_8          1  With all this stuff going down at the moment w...
1       2381_9          1  \The Classic War of the Worlds\" by Timothy Hi...
2       7759_3          0  The film starts with a manager (Nicholas Bell)...
3       3630_4          0  It must be assumed that those who praised this...
4       9495_8          1  Superbly trashy and wondrously unpretentious 8...
...        ...        ...                                                ...
24995   3453_3          0  It seems like more consideration has gone into...
24996   5064_1          0  I don't believe they made this film. Completel...
24997  10905_3          0  Guy is a loser. Can't get girls, needs to buil...
24998  10194_3          0  This 30 minute documentary Buñuel made in the ...
24999   8478_8          1  I saw this movie as a child and it broke my he...

[25000 rows x 3 columns]

In [3]:
tf

id                                             review
0      12311_10  Naturally in a film who's main themes are of m...
1        8348_2  This movie is a disaster within a disaster fil...
2        5828_4  All in all, this is a movie for kids. We saw i...
3        7186_2  Afraid of the Dark left me with the impression...
4       12128_7  A very accurate depiction of small time mob li...
...         ...                                                ...
24995   2155_10  Sony Pictures Classics, I'm looking at you! So...
24996     59_10  I always felt that Ms. Merkerson had never got...
24997    2531_1  I was so disappointed in this movie. I am very...
24998    7772_8  From the opening sequence, filled with black a...
24999  11465_10  This is a great horror film for people who don...

[25000 rows x 2 columns]

In [4]:
del df['id']
del tf['id']

In [5]:
df.describe()

sentiment
count  25000.00000
mean       0.50000
std        0.50001
min        0.00000
25%        0.00000
50%        0.50000
75%        1.00000
max        1.00000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   sentiment  25000 non-null  int64 
 1   review     25000 non-null  object
dtypes: int64(1), object(1)
memory usage: 390.8+ KB


In [7]:
df['review'][0]

"With all this stuff going down at the moment with MJ i've started listening to his music, watching the odd documentary here and there, watched The Wiz and watched Moonwalker again. Maybe i just want to get a certain insight into this guy who i thought was really cool in the eighties just to maybe make up my mind whether he is guilty or innocent. Moonwalker is part biography, part feature film which i remember going to see at the cinema when it was originally released. Some of it has subtle messages about MJ's feeling towards the press and also the obvious message of drugs are bad m'kay.<br /><br />Visually impressive but of course this is all about Michael Jackson so unless you remotely like MJ in anyway then you are going to hate this and find it boring. Some may call MJ an egotist for consenting to the making of this movie BUT MJ and most of his fans would say that he made it for the fans which if true is really nice of him.<br /><br />The actual feature film bit when it finally sta

# Text Cleaning

In [8]:
#remove html tags
import re
def clean_html(text):
    clean=re.compile('<.*#?/>')
    return re.sub(clean,'', text)

In [9]:
df['review']=df['review'].apply(clean_html)
tf['review']=tf['review'].apply(clean_html)

In [10]:
#remove special character
def remove_char(text):
    x=''
    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x+ " "
    return x
df['review']=df['review'].apply(remove_char)
tf['review']=tf['review'].apply(remove_char)

In [11]:
#convert into lower case
def convert_lower(text):
    return text.lower()


In [12]:
df['review']=df['review'].apply(convert_lower)
tf['review']=tf['review'].apply(convert_lower)

In [13]:
df['review'][0]

'with all this stuff going down at the moment with mj i ve started listening to his music  watching the odd documentary here and there  watched the wiz and watched moonwalker again  maybe i just want to get a certain insight into this guy who i thought was really cool in the eighties just to maybe make up my mind whether he is guilty or innocent  moonwalker is part biography  part feature film which i remember going to see at the cinema when it was originally released  some of it has subtle messages about mj s feeling towards the press and also the obvious message of drugs are bad m kay bottom line  this movie is for people who like mj on one level or another  which i think is most people   if not  then stay away  it does try and give off a wholesome message and ironically mj s bestest buddy in this movie is a girl  michael jackson is truly one of the most talented people ever to grace this planet but is he guilty  well  with all the attention i ve gave this subject    hmmm well i don 

In [14]:
import nltk

In [15]:
from nltk.corpus import stopwords

def remove_stopwords(text):
    x=[]
    for i in text.split():
        if i not in stopwords.words('english'):
            x.append(i)
    y=x[:]
    x.clear()
    return y

In [16]:
df['review']=df['review'].apply(remove_stopwords) 
tf['review']=tf['review'].apply(remove_stopwords) 

In [17]:
df

sentiment                                             review
0              1  [stuff, going, moment, mj, started, listening,...
1              1  [classic, war, worlds, timothy, hines, enterta...
2              0  [film, starts, manager, nicholas, bell, giving...
3              0  [must, assumed, praised, film, greatest, filme...
4              1  [superbly, trashy, wondrously, unpretentious, ...
...          ...                                                ...
24995          0  [seems, like, consideration, gone, imdb, revie...
24996          0  [believe, made, film, completely, unnecessary,...
24997          0  [guy, loser, get, girls, needs, build, picked,...
24998          0  [30, minute, documentary, buñuel, made, early,...
24999          1  [saw, movie, child, broke, heart, story, unfin...

[25000 rows x 2 columns]

In [18]:
tf

review
0      [naturally, film, main, themes, mortality, nos...
1      [movie, disaster, within, disaster, film, full...
2      [movie, kids, saw, tonight, child, loved, one,...
3      [afraid, dark, left, impression, several, diff...
4      [accurate, depiction, small, time, mob, life, ...
...                                                  ...
24995  [sony, pictures, classics, looking, sony, got,...
24996  [always, felt, ms, merkerson, never, gotten, r...
24997  [disappointed, movie, familiar, case, read, ma...
24998  [opening, sequence, filled, black, white, shot...
24999  [great, horror, film, people, want, vomit, ret...

[25000 rows x 1 columns]

In [19]:
#stemming
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [20]:
y=[]
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z

In [21]:
df['review']=df['review'].apply(stem_words)
tf['review']=tf['review'].apply(stem_words)

In [22]:
df

sentiment                                             review
0              1  [stuff, go, moment, mj, start, listen, music, ...
1              1  [classic, war, world, timothi, hine, entertain...
2              0  [film, start, manag, nichola, bell, give, welc...
3              0  [must, assum, prais, film, greatest, film, ope...
4              1  [superbl, trashi, wondrous, unpretenti, 80, ex...
...          ...                                                ...
24995          0  [seem, like, consider, gone, imdb, review, fil...
24996          0  [believ, made, film, complet, unnecessari, fir...
24997          0  [guy, loser, get, girl, need, build, pick, str...
24998          0  [30, minut, documentari, buñuel, made, earli, ...
24999          1  [saw, movi, child, broke, heart, stori, unfini...

[25000 rows x 2 columns]

In [23]:
tf

review
0      [natur, film, main, theme, mortal, nostalgia, ...
1      [movi, disast, within, disast, film, full, gre...
2      [movi, kid, saw, tonight, child, love, one, po...
3      [afraid, dark, left, impress, sever, differ, s...
4      [accur, depict, small, time, mob, life, film, ...
...                                                  ...
24995  [soni, pictur, classic, look, soni, got, right...
24996  [alway, felt, ms, merkerson, never, gotten, ro...
24997  [disappoint, movi, familiar, case, read, mark,...
24998  [open, sequenc, fill, black, white, shot, remi...
24999  [great, horror, film, peopl, want, vomit, retc...

[25000 rows x 1 columns]

In [24]:
def join_b(linput):
    return " ".join(linput)

In [25]:
df['review']=df['review'].apply(join_b)
tf['review']=tf['review'].apply(join_b)

In [26]:
df

sentiment                                             review
0              1  stuff go moment mj start listen music watch od...
1              1  classic war world timothi hine entertain film ...
2              0  film start manag nichola bell give welcom inve...
3              0  must assum prais film greatest film opera ever...
4              1  superbl trashi wondrous unpretenti 80 exploit ...
...          ...                                                ...
24995          0  seem like consider gone imdb review film went ...
24996          0  believ made film complet unnecessari first fil...
24997          0  guy loser get girl need build pick stronger su...
24998          0  30 minut documentari buñuel made earli 1930 on...
24999          1  saw movi child broke heart stori unfinish end ...

[25000 rows x 2 columns]

In [27]:
tf

review
0      natur film main theme mortal nostalgia loss in...
1      movi disast within disast film full great acti...
2      movi kid saw tonight child love one point kid ...
3      afraid dark left impress sever differ screenpl...
4      accur depict small time mob life film new jers...
...                                                  ...
24995  soni pictur classic look soni got right harri ...
24996  alway felt ms merkerson never gotten role fit ...
24997  disappoint movi familiar case read mark fuhrma...
24998  open sequenc fill black white shot reminisc go...
24999  great horror film peopl want vomit retch gore ...

[25000 rows x 1 columns]

In [28]:
X=df.iloc[:,-1].values
Y=df.iloc[:,0].values

In [29]:
X.shape

(25000,)

In [30]:
X

array(['stuff go moment mj start listen music watch odd documentari watch wiz watch moonwalk mayb want get certain insight guy thought realli cool eighti mayb make mind whether guilti innoc moonwalk part biographi part featur film rememb go see cinema origin releas subtl messag mj feel toward press also obviou messag drug bad kay bottom line movi peopl like mj one level anoth think peopl stay away tri give wholesom messag iron mj bestest buddi movi girl michael jackson truli one talent peopl ever grace planet guilti well attent gave subject hmmm well know peopl differ behind close door know fact either extrem nice stupid guy one sickest liar hope latter',
       'classic war world timothi hine entertain film obvious goe great effort length faith recreat h g well classic book mr hine succe watch film appreci fact standard predict hollywood fare come everi year e g spielberg version tom cruis slightest resembl book obvious everyon look differ thing movi envis amateur critic look critic e

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=1000)


In [32]:
X=cv.fit_transform(df['review']).toarray()
X2=cv.fit_transform(tf['review']).toarray()

In [33]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [34]:
X.shape

(25000, 1000)

In [35]:
Y

array([1, 1, 0, ..., 0, 0, 1], dtype=int64)

In [36]:
Y.shape

(25000,)

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)  # 80% training, 20% testing


In [38]:
X_train.shape

(20000, 1000)

In [39]:
X_test.shape

(5000, 1000)

In [40]:
Y_train.shape

(20000,)

In [41]:
Y_test.shape

(5000,)

In [42]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB


In [43]:
clf1=GaussianNB()
clf2=MultinomialNB()
clf3=BernoulliNB()

In [44]:
clf1.fit(X_train,Y_train)

GaussianNB()

In [45]:
clf2.fit(X_train,Y_train)

MultinomialNB()

In [46]:
clf3.fit(X_train,Y_train)

BernoulliNB()

In [47]:
pred1=clf1.predict(X_test)

In [48]:
pred2=clf2.predict(X_test)

In [49]:
pred3=clf3.predict(X_test)

In [50]:
from sklearn.metrics import accuracy_score

In [51]:
print("GaussianNB accuracy score",accuracy_score(Y_test,pred1))
print("MultinomialNB accuracy score",accuracy_score(Y_test,pred2))
print("BernoulliNB accuracy score",accuracy_score(Y_test,pred3))

GaussianNB accuracy score 0.779
MultinomialNB accuracy score 0.812
BernoulliNB accuracy score 0.8116


# Working on sample dataset


In [52]:
pred2=clf2.predict(X2)

In [53]:
pred2

array([1, 0, 0, ..., 1, 0, 0], dtype=int64)